#!/usr/bin/env bash
# Build an uploadable ZIP of a skill for claude.ai/customize/skills.
#
# Why this exists: Claude Cowork runs shell commands in a sandbox that does
# NOT auto-discover .claude/skills/ from a mounted folder the way Claude
# Code does (see docs/auth.md -> "Cowork as a host"). A Cowork user instead
# uploads a personal-skill ZIP at claude.ai/customize/skills; this script
# builds that ZIP from a self-contained skill folder under skills/.
#
# Usage:
#   bash scripts/package-skill.sh <skill-name>
#   bash scripts/package-skill.sh            # only if exactly one skill exists
#
# Output:
#   dist/<skill-name>-<short-git-sha>.zip
#
# A small stamp file (_PACKAGED_FROM.txt) is written at the top level of the
# zipped skill folder recording the git short SHA and UTC packaging time --
# nothing else makes it visible later that an uploaded ZIP has drifted from
# a since-updated clone.

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/.." && pwd)"
skills_root="$repo_root/skills"

command -v git >/dev/null 2>&1 || { echo "Error: 'git' is required (not found on PATH)." >&2; exit 1; }
if ! command -v zip >/dev/null 2>&1 && ! command -v python3 >/dev/null 2>&1; then
  echo "Error: need either 'zip' or 'python3' on PATH to build the archive." >&2
  exit 1
fi

[ -d "$skills_root" ] || { echo "Error: no skills/ directory at $skills_root." >&2; exit 1; }

# Resolve which skill to package. A skill is any skills/<name>/ containing a
# SKILL.md -- skills/_template/ has one too, so it is packageable on purpose
# (useful for checking the scaffold zips cleanly) but never auto-selected.
list_skills() {
  local d
  for d in "$skills_root"/*/; do
    [ -f "${d}SKILL.md" ] || continue
    basename "$d"
  done
}

# No arrays / mapfile here on purpose: macOS still ships bash 3.2 as
# /bin/bash, where `mapfile` does not exist and `${#arr[@]}` on an empty
# array trips `set -u`. A newline-delimited string works on every host.
skill_name="${1:-}"
if [ -z "$skill_name" ]; then
  candidates="$(list_skills | grep -v '^_' || true)"
  n_candidates="$(printf '%s' "$candidates" | grep -c . || true)"
  if [ "$n_candidates" -eq 1 ]; then
    skill_name="$candidates"
  elif [ "$n_candidates" -eq 0 ]; then
    echo "Error: no skill found under skills/ (need skills/<name>/SKILL.md)." >&2
    exit 1
  else
    echo "Error: more than one skill under skills/ -- name the one to package:" >&2
    printf '%s\n' "$candidates" | sed 's/^/  /' >&2
    exit 2
  fi
fi

skill_dir="$skills_root/$skill_name"
if [ ! -f "$skill_dir/SKILL.md" ]; then
  echo "Error: skills/$skill_name/SKILL.md not found." >&2
  echo "Available:" >&2
  list_skills | sed 's/^/  /' >&2
  exit 1
fi

# --- Warn (not fail) on uncommitted changes in the skill dir -- the SHA we
# --- stamp below reflects the last commit, not the working tree. Checked
# --- BEFORE the stamp file is written (below), so this run's own stamp file
# --- never triggers a false positive here. ---
short_sha="unknown"
if git -C "$repo_root" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  if [ -n "$(git -C "$repo_root" status --porcelain -- "$skill_dir" 2>/dev/null)" ]; then
    echo "Warning: uncommitted changes in skills/${skill_name}/ -- the packaged SHA will not reflect them." >&2
  fi
  short_sha="$(git -C "$repo_root" rev-parse --short HEAD 2>/dev/null || echo "unknown")"
else
  echo "Warning: $repo_root is not a git repository -- stamping SHA as 'unknown'." >&2
fi

dist_dir="$repo_root/dist"
mkdir -p "$dist_dir"
zip_path="$dist_dir/${skill_name}-${short_sha}.zip"
rm -f "$zip_path"

# Stamp version/provenance inside the zipped skill folder, at the top level,
# under a name unlikely to collide with existing skill content. Always
# cleaned up afterward (even on failure) so it never lingers as a stray
# untracked file in the working tree.
stamp_file="$skill_dir/_PACKAGED_FROM.txt"
packaged_at="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
cat > "$stamp_file" <<EOF
Packaged from git commit: ${short_sha}
Packaged at (UTC):        ${packaged_at}

Generated by scripts/package-skill.sh and stamped into every uploaded ZIP so
a stale claude.ai/customize/skills upload can be compared against a
since-updated clone of this repo. Safe to delete; regenerated on the next
package-skill.sh run.
EOF
trap 'rm -f "$stamp_file"' EXIT

make_zip() { # make_zip <zip_path> <parent_dir_of_skill> <skill_name>
  local zpath="$1" workdir="$2" name="$3"
  if command -v zip >/dev/null 2>&1; then
    ( cd "$workdir" && zip -r -X -q "$zpath" "$name" \
        -x "*.DS_Store" -x "*/__pycache__/*" -x "*.pyc" )
  else
    "${SIGMA_PYTHON:-python3}" - "$zpath" "$workdir" "$name" <<'PYEOF'
import os, sys, zipfile

zpath, workdir, name = sys.argv[1], sys.argv[2], sys.argv[3]
root = os.path.join(workdir, name)
skip_dirs = {"__pycache__"}
with zipfile.ZipFile(zpath, "w", zipfile.ZIP_DEFLATED) as zf:
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in skip_dirs]
        for fn in filenames:
            if fn == ".DS_Store" or fn.endswith(".pyc"):
                continue
            full = os.path.join(dirpath, fn)
            arc = os.path.relpath(full, workdir)
            zf.write(full, arc)
PYEOF
  fi
}

make_zip "$zip_path" "$skills_root" "$skill_name"

echo "$zip_path"
