#!/usr/bin/env python3
"""Prove a plugin renders BOUND data, not its own fallback -- with no Sigma.

    python3 scripts/verify-plugin-binding.py <plugin-name> [--data FILE]

Writes a self-contained harness page to plugins/_harness/<name>.html and
prints the URL to open. Needs no Sigma login, no deploy, no registration and
no network: it runs entirely against the local plugin file.

WHY THIS EXISTS
    The kit's own rule is "if the plugin shows its demo data in Sigma, the
    binding is wrong" -- but checking that needs eyes on the rendered iframe,
    and the in-app browser is not signed in to Sigma. So the usual proof was
    an HTTP 200 from publish, which is exactly the thing the kit warns is
    meaningless. A plugin whose client never initialises publishes cleanly,
    renders its fallback, and screenshots perfectly.

    This runs the plugin's real code against the real data shape Sigma sends
    (column-keyed parallel arrays, NOT row objects) and compares the bound
    render against the fallback render. Run it BEFORE deploy: deploy and
    register are the irreversible steps, since PATCH /v2/plugins/{id} cannot
    change a plugin's url.

HOW IT DECIDES
    It renders the plugin twice, in two isolated iframes:
      A. with no element bound   -> whatever the plugin falls back to
      B. with the real rows      -> what a workbook would show
    If A and B are identical, the plugin is ignoring its bindings. That test
    needs no knowledge of the plugin's markup, so it works for any archetype.

READING THE RESULT
    The page shows a report, and also sets:
      document.title      "HARNESS PASS" / "HARNESS FAIL"
      window.__HARNESS__  { pass, checks: [{name, ok, detail}], ... }
    so one javascript_tool call or a glance at the tab title is enough.
"""

import argparse
import importlib.util
import json
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
HARNESS_DIR = REPO / "plugins" / "_harness"


def load_builder():
    path = REPO / "scripts" / "build-plugin-workbook.py"
    spec = importlib.util.spec_from_file_location("_bpw", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


PAGE = r"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>HARNESS RUNNING</title>
<!--
  GENERATED by scripts/verify-plugin-binding.py -- do not edit, re-run instead.

  Renders __NAME__ twice in isolated iframes (unbound vs bound) and compares.
  Nothing here talks to Sigma; the mock below is the entire SDK surface the
  plugin gets.
-->
<style>
  body{font:13px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;
       margin:0;padding:18px;color:#1f2937;background:#fff}
  h1{font-size:15px;margin:0 0 2px}
  .sub{color:#6b7280;font-size:11px;margin-bottom:14px}
  .verdict{display:inline-block;font-weight:800;font-size:12px;letter-spacing:.06em;
           padding:4px 10px;border-radius:4px;margin-bottom:14px}
  .verdict.pass{background:#dcfce7;color:#166534}
  .verdict.fail{background:#fee2e2;color:#991b1b}
  table{border-collapse:collapse;width:100%;font-size:12px}
  td{padding:5px 8px;border-bottom:1px solid #f1f3f5;vertical-align:top}
  td.s{width:24px;font-weight:800}
  td.n{width:190px;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;color:#374151}
  .y{color:#16a34a}.n2{color:#dc2626}.w{color:#d97706}
  .frames{display:flex;gap:14px;margin-top:18px}
  .frames>div{flex:1;min-width:0}
  .cap{font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.07em;
       color:#6b7280;margin-bottom:5px}
  iframe{width:100%;height:340px;border:1px solid #e5e7eb;border-radius:5px;background:#fff}
</style>
</head>
<body>
<h1>Binding harness &mdash; __NAME__</h1>
<div class="sub">Left: nothing bound (the plugin's fallback). Right: the real rows, in Sigma's column-keyed shape.</div>
<div id="verdict" class="verdict">running&hellip;</div>
<table id="report"></table>
<div class="frames">
  <div><div class="cap">A &middot; unbound</div><iframe id="fa"></iframe></div>
  <div><div class="cap">B &middot; bound</div><iframe id="fb"></iframe></div>
</div>

<script type="application/json" id="payload">__PAYLOAD__</script>
<script>
(async function(){
  "use strict";
  const P = JSON.parse(document.getElementById('payload').textContent);
  const checks = [];
  const add = (name, ok, detail) => checks.push({ name, ok, detail });

  // --- load the plugin's own source -------------------------------------
  let html;
  try {
    html = await fetch(P.pluginUrl, { cache: 'no-store' }).then(r => {
      if (!r.ok) throw new Error('HTTP ' + r.status);
      return r.text();
    });
  } catch (e) {
    add('plugin-source', false, 'could not fetch ' + P.pluginUrl + ': ' + e.message);
    return finish();
  }
  add('plugin-source', true, P.pluginUrl);

  // The biggest inline <script> (no src) is the plugin. Pull it out and strip
  // ALL script tags from the shell: srcdoc executes inline scripts, and we
  // need to install the mock BEFORE the plugin runs.
  const inline = [...html.matchAll(/<script(?![^>]*\bsrc\b)[^>]*>([\s\S]*?)<\/script>/gi)]
                   .map(m => m[1]);
  if (!inline.length) {
    add('plugin-script', false, 'no inline <script> found -- is this a bundled '
        + 'React archetype? Build it and point --plugin-url at dist/');
    return finish();
  }
  const code = inline.reduce((a, b) => (b.length > a.length ? b : a), '');
  const shell = html.replace(/<script[\s\S]*?<\/script>/gi, '');
  add('plugin-script', true, code.length + ' bytes of inline plugin code');

  // --- the mock: the entire SDK surface the plugin sees ------------------
  // Records what the plugin actually did, so a silent no-op is visible.
  function makeClient(cfg){
    const seen = { panel: null, subscribedTo: null, read: new Set(), loading: [] };
    // A Proxy on cfg records which declared bindings the plugin really reads.
    const proxied = new Proxy(cfg, { get(t, k){ seen.read.add(String(k)); return t[k]; } });
    const client = {
      sigmaEnv: 'author',
      style: { backgroundColor: '#ffffff' },
      config: {
        configureEditorPanel(defs){ seen.panel = defs; },
        setLoadingState(v){ seen.loading.push(!!v); },
        subscribe(cb){ cb(proxied); },
        get(){ return proxied; },
        getKey(k){ return proxied[k]; },
        set(){}, setKey(){},
        getVariable(){ return null; },
        setVariable(){},
        subscribeToWorkbookVariable(){ return () => {}; },
        triggerAction(){}, registerEffect(){}
      },
      elements: {
        subscribeToElementData(id, cb){
          seen.subscribedTo = id;
          // Sigma delivers an object of parallel arrays keyed by column id --
          // not row objects. Getting this shape wrong is the usual reason a
          // plugin renders nothing with a perfectly valid binding.
          cb(id ? P.data : {});
          return () => {};
        },
        subscribeToElementColumns(id, cb){ cb(P.columns); return () => {}; },
        getElementColumns(){ return Promise.resolve(P.columns); }
      }
    };
    return { client, seen };
  }

  function render(cfg){
    return new Promise(resolve => {
      const frame = document.getElementById(cfg.__frame);
      const built = makeClient(cfg);
      frame.addEventListener('load', () => {
        const w = frame.contentWindow;
        const errors = [];
        w.onerror = (m) => { errors.push(String(m)); };
        w.SigmaPlugin = { client: built.client };
        try { w.eval(code); }
        catch (e) { errors.push(String(e && e.message || e)); }
        // Let subscribe callbacks, rAF and transitions settle.
        setTimeout(() => resolve({
          text: (w.document.body ? w.document.body.innerText : '').replace(/\s+/g, ' ').trim(),
          errors, seen: built.seen
        }), 350);
      }, { once: true });
      frame.srcdoc = shell;
    });
  }

  // A: nothing bound. B: the real rows.
  const unboundCfg = Object.assign({}, P.cfg, { __frame: 'fa' });
  delete unboundCfg.source;
  P.bindings.forEach(b => delete unboundCfg[b]);
  const A = await render(unboundCfg);
  const B = await render(Object.assign({}, P.cfg, { __frame: 'fb' }));

  // --- assertions --------------------------------------------------------
  add('no-runtime-errors', B.errors.length === 0,
      B.errors.length ? B.errors.join(' | ') : 'clean render with data bound');

  add('configures-editor-panel', !!B.seen.panel,
      B.seen.panel ? B.seen.panel.length + ' panel entries declared'
                   : 'never called configureEditorPanel -- the client is not being used');

  add('subscribes-to-element', B.seen.subscribedTo === P.cfg.source,
      B.seen.subscribedTo
        ? 'subscribed to ' + B.seen.subscribedTo
        : 'never called subscribeToElementData -- it will never receive rows');

  const readable = P.bindings.filter(b => B.seen.read.has(b));
  const ignored = P.bindings.filter(b => !B.seen.read.has(b));
  add('reads-its-bindings', ignored.length === 0,
      ignored.length ? 'declared but never read: ' + ignored.join(', ')
                     : 'all ' + readable.length + ' declared binding(s) read from config');

  add('renders-something', B.text.length > 0,
      B.text.length ? B.text.length + ' chars rendered' : 'rendered an empty body');

  // The load-bearing one: if binding data changes nothing, it is ignoring it.
  add('bound-differs-from-fallback', B.text !== A.text,
      B.text === A.text
        ? 'IDENTICAL to the unbound render -- the plugin is showing fallback '
          + 'data and ignoring the bound columns'
        : 'bound render differs from the fallback render');

  // Content proof: a label that exists only in the real rows must appear.
  const disc = P.labels.filter(v => v && !A.text.includes(v));
  if (!disc.length) {
    add('real-values-present', true,
        'WARN: every real label also appears in the fallback render, so content '
        + 'cannot discriminate. Relying on the checks above.');
    checks[checks.length - 1].warn = true;
  } else {
    const hit = disc.filter(v => B.text.includes(v));
    add('real-values-present', hit.length > 0,
        hit.length ? hit.length + '/' + disc.length + ' fallback-absent label(s) '
                     + 'rendered, e.g. "' + hit[0] + '"'
                   : 'none of the ' + disc.length + ' labels unique to the real data '
                     + 'were rendered, e.g. "' + disc[0] + '"');
  }

  const present = P.labels.filter(v => v && B.text.includes(v)).length;
  add('label-coverage', true, present + '/' + P.labels.length
      + ' label value(s) found in the bound render');
  checks[checks.length - 1].info = true;

  finish();

  function finish(){
    const hard = checks.filter(c => !c.info && !c.warn);
    const pass = hard.every(c => c.ok);
    window.__HARNESS__ = { pass, plugin: P.name, rows: P.rowCount, checks };
    document.title = pass ? 'HARNESS PASS' : 'HARNESS FAIL';
    const v = document.getElementById('verdict');
    v.textContent = pass ? 'PASS — renders bound data'
                         : 'FAIL — ' + hard.filter(c => !c.ok).length + ' check(s) failed';
    v.className = 'verdict ' + (pass ? 'pass' : 'fail');
    document.getElementById('report').innerHTML = checks.map(c => {
      const sym = c.info ? '<span class="w">i</span>'
                : c.warn ? '<span class="w">!</span>'
                : c.ok   ? '<span class="y">✓</span>'
                         : '<span class="n2">✗</span>';
      return '<tr><td class="s">' + sym + '</td><td class="n">' + c.name
           + '</td><td>' + String(c.detail || '') + '</td></tr>';
    }).join('');
  }
})();
</script>
</body>
</html>
"""


def main():
    ap = argparse.ArgumentParser(
        description="Generate a local harness proving a plugin renders bound "
                    "data rather than its own fallback. No Sigma needed.")
    ap.add_argument("name", help="plugin directory name under plugins/")
    ap.add_argument("--data", help="rows to bind (.csv/.tsv or JSON array). "
                                   "Defaults to rows synthesized from the panel.")
    ap.add_argument("--rows", type=int, default=8,
                    help="how many rows to synthesize when --data is absent")
    ap.add_argument("--plugin-url", default=None,
                    help="override the served path to the plugin HTML")
    ap.add_argument("--port", type=int, default=7824, help="port you will serve on")
    args = ap.parse_args()

    plugin_dir = REPO / "plugins" / args.name
    if not plugin_dir.is_dir():
        print("verify-plugin-binding: no such plugin: %s" % plugin_dir, file=sys.stderr)
        return 2

    builder = load_builder()
    src_file = builder.find_plugin_source(str(plugin_dir))
    if not src_file:
        print("verify-plugin-binding: no configureEditorPanel under %s" % plugin_dir,
              file=sys.stderr)
        return 2

    entries = builder.parse_editor_panel(
        src_file.read_text(encoding="utf-8", errors="replace"))
    if entries is None:
        print("verify-plugin-binding: could not parse configureEditorPanel; run "
              "preflight-plugin.py first", file=sys.stderr)
        return 2
    primary, cols, _extra = builder.bindings_from_panel(entries)
    if not primary or len(cols) < 2:
        print("verify-plugin-binding: need an element binding and >=2 column "
              "bindings; run preflight-plugin.py first", file=sys.stderr)
        return 2

    # Rows, then the exact reshaping the real workbook produces: column ids
    # come from the builder's own column_id(), so the harness and production
    # agree on the keys.
    if args.data:
        rows = builder.load_rows(args.data)
        described = "%d row(s) from %s" % (len(rows), args.data)
    else:
        rows = builder.synthesize_rows(cols, max(1, args.rows))
        described = "%d synthesized row(s) (pass --data for real ones)" % len(rows)

    headers = []
    for row in rows:
        for k in row:
            if k not in headers:
                headers.append(k)

    binding_names = [n for n, _ in cols]
    missing = [n for n in binding_names if n not in headers]
    if missing:
        print("verify-plugin-binding: the data has no column named %s.\n"
              "  Bindings must match data headers exactly. Headers: %s"
              % (", ".join(repr(m) for m in missing), ", ".join(headers)),
              file=sys.stderr)
        return 2

    data = {}
    for h in headers:
        cid = builder.column_id(h)
        kind = builder.infer_type([r.get(h) for r in rows])
        vals = []
        for r in rows:
            v = r.get(h)
            if kind in ("int", "float"):
                try:
                    v = float(v) if kind == "float" else int(float(v))
                except (TypeError, ValueError):
                    v = None
            vals.append(v)
        data[cid] = vals

    cfg = {"source": "tbl-data"}
    for n in binding_names:
        cfg[n] = builder.column_id(n)

    label_col = binding_names[0]
    labels = [str(r.get(label_col)) for r in rows if r.get(label_col) not in (None, "")]

    payload = {
        "name": args.name,
        "pluginUrl": args.plugin_url or ("../%s/index.html" % args.name),
        "cfg": cfg,
        "bindings": binding_names,
        "data": data,
        "columns": {builder.column_id(h): {"name": h} for h in headers},
        "labels": labels,
        "rowCount": len(rows),
    }

    HARNESS_DIR.mkdir(parents=True, exist_ok=True)
    out = HARNESS_DIR / ("%s.html" % args.name)
    blob = json.dumps(payload).replace("</", "<\\/")
    out.write_text(PAGE.replace("__NAME__", args.name).replace("__PAYLOAD__", blob),
                   encoding="utf-8")

    url = "http://localhost:%d/_harness/%s.html" % (args.port, args.name)
    print("harness: %s" % out.relative_to(REPO))
    print("  data:  %s" % described)
    print("  binds: %s" % ", ".join("%s=%s" % (n, cfg[n]) for n in binding_names))
    print()
    print("Serve the plugins directory, then open the harness:")
    print("  npx serve -l %d %s" % (args.port, (REPO / "plugins")))
    print("  %s" % url)
    print()
    print("PASS/FAIL lands in the page, in document.title, and in window.__HARNESS__.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
